name: Build Deploy

on:
  push:
    branches:
      - 'main'

env:
  TARGET_DIR: dist/analog/public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy 404.html
        run: cp dist/analog/public/index.html dist/analog/public/404.html
      - name: Deploy Website
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npx angular-cli-ghpages --no-silent --dir="${{env.TARGET_DIR}}"
