name: Build Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Copy 404.html
        run: cp dist/analog/public/index.html dist/analog/public/404.html

      - name: Deploy Website
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          bunx angular-cli-ghpages --no-silent --dir="dist/analog/public"
